### ISSUE TITLE
Handler 'create_fn' and 'on_delete' failed on deleting clustersecret

### ISSUE THREAD

**Issue by CasparChou** [zakkg3/ClusterSecret#11]
errors occurred when deleting clustersecret
and it can not be deleted, even --force

command:
```
$ kubectl delete -f tls-my-cert.yaml
> clustersecret.clustersecret.io "tls-my-cert" deleted
(hang)
```

```
2020-09-01 06:22:53,762] kopf.objects         [ERROR   ] [clustersecret/tls-my-cert] Handler 'create_fn' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 44, in create_fn
    matchedns = get_ns_list(logger,body,v1)
  File "/src/handlers.py", line 83, in get_ns_list
    if re.match(matchns, ns.metadata.name):
  File "/usr/local/lib/python3.7/re.py", line 175, in match
    return _compile(pattern, flags).match(string)
  File "/usr/local/lib/python3.7/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/local/lib/python3.7/sre_parse.py", line 645, in _parse
    source.tell() - here + len(this))
re.error: nothing to repeat at position 0
[2020-09-01 06:23:08,195] kopf.objects         [ERROR   ] [clustersecret/tls-my-cert] Handler 'on_delete' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 148, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/handlers.py", line 8, in on_delete
    syncedns = body['status']['create_fn']['syncedns']
KeyError: 'create_fn'
[2020-09-01 06:24:08,351] kopf.objects         [ERROR   ] [clustersecret/tls-my-cert] Handler 'on_delete' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 148, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/handlers.py", line 8, in on_delete
    syncedns = body['status']['create_fn']['syncedns']
KeyError: 'create_fn'
[2020-09-01 06:25:08,523] kopf.objects         [ERROR   ] [clustersecret/tls-my-cert] Handler 'on_delete' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 148, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/handlers.py", line 8, in on_delete
    syncedns = body['status']['create_fn']['syncedns']
KeyError: 'create_fn'
```

after restart the pod

```
[2020-09-01 06:32:48,788] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2020-09-01 06:32:48,789] kopf.activities.auth [INFO    ] Activity 'login_via_pykube' succeeded.
[2020-09-01 06:32:48,790] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
[2020-09-01 06:32:48,790] kopf.reactor.activit [INFO    ] Initial authentication has finished.
[2020-09-01 06:32:48,798] kopf.engines.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
[2020-09-01 06:32:48,940] kopf.objects         [ERROR   ] [clustersecret/tls-my-cert] Handler 'on_delete' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 148, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/handlers.py", line 8, in on_delete
    syncedns = body['status']['create_fn']['syncedns']
KeyError: 'create_fn'
```

btw, missing `Kind: ClusterSecret` field in first section on readme

**Comment by zakkg3** [comment]
Readme fixed 30d994935cc92e957f80da4c9110daf24199e7d2

Can you provide the "debug enabled" logs. (check before not to leak any password here).
https://github.com/zakkg3/ClusterSecret#debugging

thanks!

**Comment by CasparChou** [comment]
sure! it came out too many logs that I need a time to remove some information.

btw, my certificate just reach Let's encrypted rate limit, and its orders (created by cert-manager) is on "errord" status, certificate is "invalid" also

**Comment by zakkg3** [comment]
Working on a fix for this.
In the mean time you can delete the finalizer on the clustersecret object:

```
k edit csec -n default global-secret2
```

Find the finalizer sectrion and edit to 
```
finalizers: []
```

then the deletion handler should do the rest.

**Comment by CasparChou** [comment]
error seems fixed, thanks
