### ISSUE TITLE
Can't sync new namespaces

### ISSUE THREAD

**Issue by cool-tiger** [zakkg3/ClusterSecret#14]
Hello.
I taked a last version of operator https://github.com/zakkg3/ClusterSecret/blob/fef0f305577540d51c404505ae879d749547e6c2/src/handlers.py and tried to deploy it. All was well, i create clustersecret:
```
---
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: clustersecret-dev-autobp-tls-cert
  namespace: clustersecret
matchNamespace:
  - "clustersecret*"
avoidNamespaces:
  - kube-*
data:
  tls.crt: some_cert
  tls.key: some_key
```
Secrets was created in 2 namespace: clustersecret and clustersecret2. But when i tried to create new namespace clustersecret3 i got errors in operator:
```
[2020-09-04 08:16:44,580] kopf.objects         [DEBUG   ] [None/clustersecret3] Handler 'namespace_watcher' is invoked.
[2020-09-04 08:16:44,580] kopf.objects         [DEBUG   ] [None/clustersecret3] New namespace created: clustersecret3 re-syncing
[2020-09-04 08:16:44,581] kopf.objects         [ERROR   ] [None/clustersecret3] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 149, in namespace_watcher
    matcheddns = v['body']['status']['create_fn']['syncedns']
KeyError: 'create_fn'
[2020-09-04 08:16:44,583] kopf.objects         [DEBUG   ] [None/clustersecret3] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/namespace_watcher': '{"started": "2020-09-04T08:16:44.580408", "delayed": "2020-09-04T08:17:44.582888", "retries": 1, "success": false, "failure": false, "message": "\'create_fn\'"}'}}, 'status': {'kopf': {'progress': {'namespace_watcher': {'started': '2020-09-04T08:16:44.580408', 'stopped': None, 'delayed': '2020-09-04T08:17:44.582888', 'retries': 1, 'success': False, 'failure': False, 'message': "'create_fn'"}}}}}
[2020-09-04 08:16:44,610] kopf.reactor.queuein [ERROR   ] functools.partial(<function process_resource_event at 0x7f9ebab9ed40>, lifecycle=<function asap at 0x7f9ebadfe050>, registry=<kopf.toolkits.legacy_registries.SmartGlobalRegistry object at 0x7f9eb9526f10>, settings=OperatorSettings(logging=LoggingSettings(), posting=PostingSettings(enabled=True, level=20), watching=WatchingSettings(server_timeout=None, client_timeout=None, connect_timeout=None, reconnect_backoff=0.1), batching=BatchingSettings(worker_limit=None, idle_timeout=5.0, batch_window=0.1, exit_timeout=2.0), execution=ExecutionSettings(executor=<concurrent.futures.thread.ThreadPoolExecutor object at 0x7f9eb98c1350>, _max_workers=None), background=BackgroundSettings(cancellation_polling=60, instant_exit_timeout=None, instant_exit_zero_time_cycles=10), persistence=PersistenceSettings(finalizer='kopf.zalando.org/KopfFinalizerMarker', progress_storage=<kopf.storage.progress.SmartProgressStorage object at 0x7f9eb98c1490>, diffbase_storage=<kopf.storage.diffbase.AnnotationsDiffBaseStorage object at 0x7f9eb98d9bd0>)), memories=<kopf.structs.containers.ResourceMemories object at 0x7f9eb98d9e90>, resource=Resource(group='', version='v1', plural='namespaces'), event_queue=<Queue at 0x7f9eb98e1150 maxsize=0 _getters[1] tasks=11>) failed with an exception. Ignoring the event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 187, in worker
    await processor(raw_event=raw_event, replenished=replenished)
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/processing.py", line 204, in process_resource_event
    replenished=replenished,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/processing.py", line 227, in apply_reaction_outcomes
    await patching.patch_obj(resource=resource, patch=patch, body=body)
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/auth.py", line 45, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/patching.py", line 67, in patch_obj
    raise_for_status=True,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 588, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.220.128.1:443/api/v1/namespaces/clustersecret3/status')
[2020-09-04 08:16:44,713] kopf.objects         [DEBUG   ] [None/clustersecret3] Creation event: {'kind': 'Namespace', 'apiVersion': 'v1', 'metadata': {'name': 'clustersecret3', 'selfLink': '/api/v1/namespaces/clustersecret3', 'uid': '9ea022c1-4546-4b02-a711-c83519953bbf', 'resourceVersion': '68088144', 'creationTimestamp': '2020-09-04T08:16:44Z', 'annotations': {'kopf.zalando.org/namespace_watcher': '{"started": "2020-09-04T08:16:44.580408", "delayed": "2020-09-04T08:17:44.582888", "retries": 1, "success": false, "failure": false, "message": "\'create_fn\'"}'}}, 'spec': {'finalizers': ['kubernetes']}, 'status': {'phase': 'Active'}}
[2020-09-04 08:16:44,714] kopf.objects         [DEBUG   ] [None/clustersecret3] Sleeping for 59.868061 seconds for the delayed handlers.
[2020-09-04 08:16:45,346] kopf.objects         [DEBUG   ] [None/clustersecret3] Sleeping was interrupted by new changes, 59.237326397079286 seconds left.
[2020-09-04 08:16:45,449] kopf.objects         [DEBUG   ] [None/clustersecret3] Creation event: {'kind': 'Namespace', 'apiVersion': 'v1', 'metadata': {'name': 'clustersecret3', 'selfLink': '/api/v1/namespaces/clustersecret3', 'uid': '9ea022c1-4546-4b02-a711-c83519953bbf', 'resourceVersion': '68088159', 'creationTimestamp': '2020-09-04T08:16:44Z', 'annotations': {'kopf.zalando.org/namespace_watcher': '{"started": "2020-09-04T08:16:44.580408", "delayed": "2020-09-04T08:17:44.582888", "retries": 1, "success": false, "failure": false, "message": "\'create_fn\'"}', 'logging.csp.vmware.com/fluentd-status': ''}}, 'spec': {'finalizers': ['kubernetes']}, 'status': {'phase': 'Active'}}
[2020-09-04 08:16:45,452] kopf.objects         [DEBUG   ] [None/clustersecret3] Sleeping for 59.130856 seconds for the delayed handlers.
```
Help please to fix this error. Thank you.

**Comment by zakkg3** [comment]
Cant reproduce the error. 
Did you apply the file ClusterSecret/yaml/00_rbac.yaml ?
It seems there is forbidden to patch the new namespace.

But here we specify verb patch for the account "clustersecret-account" on resource namespaces...

```
  # Watch naespaces 
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [watch, list, get, patch]
```

If this is the case, please provide more info on what k8s cluster are you testing this. (minikube / docker k8s / EKS / GCP/ k3s  ... )

**Comment by cool-tiger** [comment]
I use baremetall k8s v1.16.2 cluster with docker as runtime. I tried to enable god mode for service account `clustersecret-account`.
```yaml
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
```
but have same errors in logs. I saw that namespaces with secret have annotations:
```yaml
  annotations:
    kopf.zalando.org/last-handled-configuration: '{"spec": {"finalizers": ["kubernetes"]},
      "metadata": {"annotations": {"logging.csp.vmware.com/fluentd-status": ""}}}'
    logging.csp.vmware.com/fluentd-status: ""
```
and clustersecret3 has:
```
    kopf.zalando.org/namespace_watcher: '{"started": "2020-09-07T07:57:56.367980",
      "delayed": "2020-09-07T07:58:56.368966", "retries": 1, "success": false, "failure":
      false, "message": "''create_fn''"}'
```
may be it helps for understanding problem.

**Comment by zakkg3** [comment]
I could reproduce the error. I will take a deeper look in the coming days if I have some free time 👍 
Thanks for reporting

**Comment by zakkg3** [comment]
I ve bumped version and rebuild the images. that was missing from the last PR. 

Please fetch latest changes: https://github.com/zakkg3/ClusterSecret/commit/6d6c6e77404848b2407fd8f8b177e8820bb12529 

Make shure you are pulling version 0.0.4
 

```
k create ns cluster-test
namespace/cluster-test created

k get secret -n cluster-test
NAME                  TYPE                                  DATA   AGE
cluster-test          Opaque                                0      24s
default-token-6w2j5   kubernetes.io/service-account-token   3      24s
```

```
[2020-09-09 07:41:03,970] kopf.objects         [INFO    ] [default/global-secret] Handler 'create_fn' succeeded.
[2020-09-09 07:41:03,971] kopf.objects         [INFO    ] [default/global-secret] All handlers succeeded for resuming.
[2020-09-09 07:44:40,193] kopf.objects         [INFO    ] [None/cluster-test] cloning secret in namespace cluster-test
[2020-09-09 07:44:40,205] kopf.objects         [INFO    ] [None/cluster-test] Handler 'namespace_watcher' succeeded.
[2020-09-09 07:44:40,205] kopf.objects         [INFO    ] [None/cluster-test] All handlers succeeded for creation.
```

**Comment by cool-tiger** [comment]
@zakkg3 thank you very match, all works fine. Great work.
