### ISSUE TITLE
Error "UnboundLocalError: local variable 'ns_new_list' referenced before assignment" in log (with 0.0.6)

### ISSUE THREAD

**Issue by pmorch** [zakkg3/ClusterSecret#31]
Because of #16, I'm using version 0.0.6 with the same kind cluster as in #16. After `kubectl apply -f ./yaml` I see the following errors in the log. Things look to be working though...

```
$ kubectl logs -n clustersecret clustersecret-5f98958756-xw45w
[2021-12-07 17:04:53,762] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2021-12-07 17:04:53,765] kopf.activities.auth [INFO    ] Activity 'login_via_pykube' succeeded.
[2021-12-07 17:04:53,766] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
[2021-12-07 17:04:53,767] kopf.reactor.activit [INFO    ] Initial authentication has finished.
[2021-12-07 17:04:53,781] kopf.engines.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
[2021-12-07 17:04:53,892] kopf.objects         [ERROR   ] [None/clustersecret] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 176, in namespace_watcher
    return {'syncedns': ns_new_list}
UnboundLocalError: local variable 'ns_new_list' referenced before assignment
[2021-12-07 17:04:53,900] kopf.objects         [ERROR   ] [None/default] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 176, in namespace_watcher
    return {'syncedns': ns_new_list}
UnboundLocalError: local variable 'ns_new_list' referenced before assignment
[2021-12-07 17:04:53,904] kopf.objects         [ERROR   ] [None/kube-node-lease] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 176, in namespace_watcher
    return {'syncedns': ns_new_list}
UnboundLocalError: local variable 'ns_new_list' referenced before assignment
[2021-12-07 17:04:53,908] kopf.objects         [ERROR   ] [None/kube-public] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 176, in namespace_watcher
    return {'syncedns': ns_new_list}
UnboundLocalError: local variable 'ns_new_list' referenced before assignment
[2021-12-07 17:04:53,912] kopf.objects         [ERROR   ] [None/kube-system] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 176, in namespace_watcher
    return {'syncedns': ns_new_list}
UnboundLocalError: local variable 'ns_new_list' referenced before assignment
[2021-12-07 17:04:53,917] kopf.objects         [ERROR   ] [None/local-path-storage] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 176, in namespace_watcher
    return {'syncedns': ns_new_list}
UnboundLocalError: local variable 'ns_new_list' referenced before assignment

**Comment by manuelchichi** [comment]
We solved this problem by defining the cluster secret with a matchNamespace option. I am not sure if this will work in your case. Could you share the cluster secret?

**Comment by pmorch** [comment]
I've moved on and am no longer using the project.

**Comment by zakkg3** [comment]
Can not reproduce with latests version.

```
$k create ns
error: exactly one NAME is required, got 0
See 'kubectl create namespace -h' for help and examples
$ k create ns anothernamespace
namespace/anothernamespace created
$ k get secrets -n anothernamespace
NAME                  TYPE                                  DATA   AGE
default-token-st86g   kubernetes.io/service-account-token   3      7s
global-secret         Opaque                                2      7s
```

Closing this issue.

**Comment by eduanb** [comment]
This issue is still present. To reproduce, install ClusterSecret and create a secret without a namespace filter like this one from the docs:
```yaml
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: global-secret
  namespace: my-fav-namespce
data:
  username: MTIzNDU2Cg==
  password: Nzg5MTAxMTIxMgo=
  ```
  Adding a `matchNamespace` fixed it.
