### ISSUE TITLE
How to remove ClusterSecret

### ISSUE THREAD

**Issue by mutagenspree** [zakkg3/ClusterSecret#35]
When version 0.0.8 came I changed configuration but made mistake in config. I tried to remove clustersecret but it stuck. Status of clustersecret is "Resource scheduled for deletion" and I see
 ```
2022-04-16 08:38:30,485] kopf.objects [INFO ] [clustersecret/aws-ecr-secret] Re Syncing secret aws-ecr-secret in ns cattle-fleet-system
--
[2022-04-16 08:38:30,502] kopf.objects [ERROR ] [clustersecret/aws-ecr-secret] Handler 'on_field_data/data' failed with an exception. Will retry.
 Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 283, in execute_handler_once
result = await invoke_handler(
File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 378, in invoke_handler
 result = await invocation.invoke(
 File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py", line 140, in invoke
 await asyncio.shield(future) # slightly expensive: creates tasks
 File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
 File "/src/handlers.py", line 62, in on_field_data
 response = v1.replace_namespaced_secret(name,ns,body)
File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 27733, in replace_namespaced_secret
return self.replace_namespaced_secret_with_http_info(name, namespace, body, **kwargs) # noqa: E501
 File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 27836, in replace_namespaced_secret_with_http_info
return self.api_client.call_api(
File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
return self.__call_api(resource_path, method,
File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
response_data = self.request(
File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 399, in request
return self.rest_client.PUT(url,
 File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 285, in PUT
return self.request("PUT", url,
 File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234, in request
raise ApiException(http_resp=r)
 kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request


HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ID', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'UID', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'UID', 'Date': 'Sat, 16 Apr 2022 07:33:17 GMT', 'Content-Length': '405'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Secret in version \"v1\" cannot be handled as a Secret: v1.Secret.Data: base64Codec: invalid input, error found in #10 byte of ...|lueFrom\": {\"secretKe|..., bigger context ...|{\"apiVersion\": \"v1\", \"data\": {\"valueFrom\": {\"secretKeyRef\": {\"name\": \"global-secret\", \"names|...","reason":"BadRequest","code":400}
```
in clustersecret deployment's logs, I've tried to remove namespace. It was difficult, but I did. After I created NS again with new configs, I saw old clustersecret again.

I created clustersecret with new name and it seems work. But I want to delete the old

**Comment by zakkg3** [comment]
you can try to force a manual deletion by removing the finalizer on the object:

edit the cluster secret with.

```
kubectl edit csec -n clustersecret aws-ecr-secret
```

change this 

```
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
```

to this:

```
 finalizers: []
```

**Comment by mutagenspree** [comment]
It helps, Thank a lot!

Another question - Can ClusterSecret updates? In my case I've created auto renew secret because docker registry at AWS and I have to get new credentials every 6 hours. But it seems that secrets createted by ClusterSecret doesn't change

**Comment by zakkg3** [comment]
Not so far. but its an interesting use case. we will need to track the source secret for changes and re-sync in that case.
Maybe in version 0.9 or if you want to make a PR for this its also welcome :)
