### ISSUE TITLE
Option to add suffix in MatchNamespace/avoidNamespaces

### ISSUE THREAD

**Issue by sganeshr** [zakkg3/ClusterSecret#47]
I have namespaces that have the format <app_name>-<environment>.
I would like to apply a environment specific certificate and put matchnamespace as '*-qa'
It fails with below error:
---------------
[ERROR ] [clustersecret/tls-secret] Handler 'create_fn' failed with an exception. Will retry.
Error
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 283, in execute_handler_once result = await invoke_handler( File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 378, in invoke_handler result = await invocation.invoke( File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py", line 117, in invoke result = await fn(**kwargs) # type: ignore File "/src/handlers.py", line 73, in create_fn matchedns = get_ns_list(logger,body,v1) File "/src/csHelper.py", line 34, in get_ns_list if re.match(matchns, ns.metadata.name): File "/usr/local/lib/python3.9/re.py", line 191, in match return _compile(pattern, flags).match(string) File "/usr/local/lib/python3.9/re.py", line 304, in _compile p = sre_compile.compile(pattern, flags) File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile p = sre_parse.parse(p, flags) File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0) File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub itemsappend(_parse(source, state, verbose, nested + 1, File "/usr/local/lib/python3.9/sre_parse.py", line 668, in _parse raise source.error("nothing to repeat", re.error: nothing to repeat at position 0
---------------

**Comment by zakkg3** [comment]
This is a parsing error from the regex paquet, it seems your regex is wrong.
you need something like '.*-qa'.
you can play with that here https://regexr.com/

**Comment by zakkg3** [comment]
closing due to inactive issue.
I hope it is working for you. reopen if its not the case.
