### ISSUE TITLE
bug: nothing to repeat

### ISSUE THREAD

**Issue by axel7083** [zakkg3/ClusterSecret#86]
Using default `helm` chart with the following

> helm install cluster-secret ./charts/cluster-secret -n cluster-secret --create-namespace

I get this error when creating a ClusterSecret

```
[2023-09-03 09:53:11,282] kopf.objects         [ERROR   ] [example-1/simple-cluster-secret] Handler 'create_fn' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 283, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 378, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py", line 117, in invoke
    result = await fn(**kwargs)  # type: ignore
  File "/src/handlers.py", line 114, in create_fn
    matchedns = get_ns_list(logger,body,v1)
  File "/src/csHelper.py", line 66, in get_ns_list
    if re.match(matchns, ns.metadata.name):
  File "/usr/local/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/local/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)

```

**Comment by zakkg3** [comment]
con you paste here your cluster secret (ofc offuscate sensitive data).

**Comment by axel7083** [comment]
They are not any sensitive data

```yaml
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  annotations:
    kopf.zalando.org/create_fn: >-
      {"started":"2023-09-03T10:12:37.743492","delayed":"2023-09-03T10:13:37.884919","purpose":"create","retries":1,"success":false,"failure":false,"message":"nothing
      to repeat at position 0"}
    kopf.zalando.org/on_field_data.data: >-
      {"started":"2023-09-03T10:12:37.743479","stopped":"2023-09-03T10:12:37.744809","purpose":"create","retries":1,"success":true,"failure":false}
  creationTimestamp: '2023-09-03T10:12:37Z'
  finalizers:
    - kopf.zalando.org/KopfFinalizerMarker
  generation: 3
  managedFields:
    - apiVersion: clustersecret.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:username: {}
      manager: OpenAPI-Generator
      operation: Update
      time: '2023-09-03T10:12:37Z'
    - apiVersion: clustersecret.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kopf.zalando.org/create_fn: {}
            f:kopf.zalando.org/on_field_data.data: {}
          f:finalizers:
            .: {}
            v:"kopf.zalando.org/KopfFinalizerMarker": {}
        f:status:
          .: {}
          f:kopf:
            .: {}
            f:progress:
              .: {}
              f:create_fn:
                .: {}
                f:delayed: {}
                f:failure: {}
                f:message: {}
                f:purpose: {}
                f:retries: {}
                f:started: {}
                f:success: {}
              f:on_field_data/data:
                .: {}
                f:failure: {}
                f:purpose: {}
                f:retries: {}
                f:started: {}
                f:stopped: {}
                f:success: {}
      manager: kopf
      operation: Update
      time: '2023-09-03T10:12:37Z'
  name: simple-cluster-secret
  namespace: example-1
  resourceVersion: '49895'
  uid: 9122c979-fbca-4088-ba07-5fb2085a7417
  selfLink: >-
    /apis/clustersecret.io/v1/namespaces/example-1/clustersecrets/simple-cluster-secret
status:
  kopf:
    progress:
      create_fn:
        delayed: '2023-09-03T10:13:37.884919'
        failure: false
        message: nothing to repeat at position 0
        purpose: create
        retries: 1
        started: '2023-09-03T10:12:37.743492'
        success: false
      on_field_data/data:
        failure: false
        purpose: create
        retries: 1
        started: '2023-09-03T10:12:37.743479'
        stopped: '2023-09-03T10:12:37.744809'
        success: true
data:
  username: MTIzNDU2Cg==

```

**Comment by zakkg3** [comment]
can you paste here the yaml you are applying. 
It seems its incomplete clustersecret object. IE cant see matchNamespace?
if this is the case, we may have to add a verification to fail with a more style, I mean an explicit message.

**Comment by axel7083** [comment]
Yaml applied 

```yaml
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: global-secret
  namespace: example-1
data:
  username: MTIzNDU2Cg==
```

I've changed the code to

```yaml
    for matchns in matchNamespace:
        for ns in nss:
            logger.info(f"matchns: {matchns}")
            logger.info(f"ns.metadata.name {ns.metadata.name}")
            if re.match(matchns, ns.metadata.name):
                matchedns.append(ns.metadata.name)
                logger.debug(f'Matched namespaces: {ns.metadata.name} match pattern: {matchns}')
```
And got the following

```logs
[2023-09-03 10:26:00,902] kopf.objects         [INFO    ] [example-1/simple-cluster-secret] matchns: *
[2023-09-03 10:26:00,902] kopf.objects         [INFO    ] [example-1/simple-cluster-secret] ns.metadata.name cluster-secret
[2023-09-03 10:26:00,903] kopf.objects         [ERROR   ] [example-1/simple-cluster-secret] Handler 'create_fn' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 283, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 378, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py", line 117, in invoke
    result = await fn(**kwargs)  # type: ignore
  File "/src/handlers.py", line 116, in create_fn
    matchedns = get_ns_list(logger,body,v1)
  File "/src/csHelper.py", line 93, in get_ns_list
    if re.match(matchns, ns.metadata.name):
  File "/usr/local/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/local/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.9/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

**Comment by zakkg3** [comment]
I think i have a fix here : https://github.com/zakkg3/ClusterSecret/tree/fix-bad-pattern
can you confirm ?

**Comment by axel7083** [comment]
Yes good
